//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.ReadBooks = new HashSet<ReadBook>();
            this.ReadingBooks = new HashSet<ReadingBook>();
        }
    
        public string BookName { get; set; }
        public string AuthorName { get; set; }
        public byte[] CoverBook { get; set; }
        public string SeriesName { get; set; }
        public Nullable<int> NumberInSeries { get; set; }
        public string LinkToBook { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual BookReview BookReview { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadBook> ReadBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadingBook> ReadingBooks { get; set; }
    }
}
