//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookReview
    {
        public string BookName { get; set; }
        public string UserLogin { get; set; }
        public string ReviewText { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
