//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FantasyLibraryDataEntities1 : DbContext
    {
        public FantasyLibraryDataEntities1()
            : base("name=FantasyLibraryDataEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<BookReview> BookReviews { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<ReadBook> ReadBooks { get; set; }
        public virtual DbSet<ReadingBook> ReadingBooks { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
    }
}
